name: cinema-tickets

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cinema_tickets_dev
      POSTGRES_USER: cinema_tickets_dev_app
      POSTGRES_PASSWORD: ${CINEMA_TICKETS_DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - internal-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema_tickets_dev_app -d cinema_tickets_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: cinema-tickets-backend
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - public-net
      - internal-net
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CINEMA_TICKETS_DB_PASSWORD: ${CINEMA_TICKETS_DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: cinema-tickets-frontend
    build:
      context: ./frontend
      args:
        CONFIG: ${CONFIG:-development}
    ports:
      - "4200:80"
    networks:
      - public-net
    depends_on:
      - backend

networks:
  public-net:
    driver: bridge
  internal-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
