spring:
  config:
    activate:
      on-profile: prod # rodar o projeto com docker sem seeder

  flyway:
    locations:
    - classpath:db/migration
    baseline-on-migrate: false

  datasource:
    url: ${CINEMA_TICKETS_DB_URL}
    username: ${CINEMA_TICKETS_DB_USERNAME}
    password: ${CINEMA_TICKETS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

app:
  seed:
    enabled: false
  errors:
    include-stacktrace: false

  bootstrap-admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:true}
    email: ${BOOTSTRAP_ADMIN_EMAIL}
    password: ${BOOTSTRAP_ADMIN_PASSWORD}
    cpf: ${BOOTSTRAP_ADMIN_CPF:00000000000}
    nome: ${BOOTSTRAP_ADMIN_NAME:Admin}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}