spring:
  application:
    name: cinema-tickets-backend
    
  datasource:
    url: ${DATABASE_URL} # Placeholder | jdbc:postgresql://localhost:PORTA/cinema_tickets
    username: ${DATABASE_USERNAME} # Placeholder
    password: ${DATABASE_PASSWORD} # Placeholder
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET} # Placeholder
  expiration: 86400000  # 24 horas em milissegundos
